version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: online-library
    expose:
      - "5000"   # Only exposed to linked services (i.e., Nginx)
    environment:
      - FLASK_ENV=production

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"  # Maps host port 80 to container port 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/usr/share/nginx/html/static:ro
    depends_on:
      - web
